version: '3.1'
services:
  demo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo:v1.0.0
    container_name: demo
    ports:
      - 8081:8080
    network_mode: host
    volumes:
      - /usr/share/nginx/userHelp:/usr/share/nginx/userHelp

